Traceback (most recent call last):
  File "/mnt/c/Users/gavin/holbertonschool-machine_learning/supervised_learning/time_series/./forecast_btc.py", line 14, in <module>
    X = np.loadtxt('/mnt/c/Users/gavin/holbertonschool-machine_learning/supervised_learning/data/X.npy')
  File "/home/gavintobin/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1085, in loadtxt
    for first_line in line_iter:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "/mnt/c/Users/gavin/holbertonschool-machine_learning/supervised_learning/time_series/./forecast_btc.py", line 14, in <module>
    X = np.loadtxt('/mnt/c/Users/gavin/holbertonschool-machine_learning/supervised_learning/data/X.npy')
  File "/home/gavintobin/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1085, in loadtxt
    for first_line in line_iter:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte